export const data = [
  {
    id: 1,
    images: ["bag2.png", "bag1.png", "bag3.png"],
    name: "Military Backpack",
    price: 36.0,
    sale: false,
    stars: 0,
    discount: 8,
    colors: ["#FFC300", "red", "#DE3163"],
    inStock: 0,
    sizes: [],
  },
  {
    id: 2,
    images: ["chair2.png", "chair1.png", "chair3.png"],
    name: "Simple Fabric Chair",
    price: 65.0,
    sale: true,
    stars: 3,
    discount: 12.0,
    colors: [],
    inStock: 3,
    sizes: [],
  },
  {
    id: 3,
    images: ["glasses.png", "glasses2.png", "glasses3.png"],
    name: "Beautiful Sunglasses",
    price: 55.0,
    sale: false,
    stars: 0,
    discount: 0,
    colors: ["black", "green", "red"],
    inStock: 6,
    sizes: [],
  },
  {
    id: 4,
    images: ["soda2.png", "soda.png", "soda3.png"],
    name: "Refreshing Drink",
    price: 24.0,
    sale: false,
    stars: 2,
    discount: 0,
    colors: [],
    inStock: 9,
    sizes: [],
  },
  {
    id: 5,
    images: ["handbag.png", "handbag2.png", "handbag3.png"],
    name: "Luxurious Ladies Handbag",
    price: 65.0,
    sale: false,
    stars: 5,
    discount: 12.0,
    colors: ["#DE3163", "gray", "black"],
    inStock: 7,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: 6,
    images: ["watch.png", "watch2.png", "watch3.png"],
    name: "Luxurious Watch",
    price: 125.0,
    sale: true,
    stars: 4,
    discount: 0,
    colors: [],
    inStock: 0,
    sizes: [],
  },
  {
    id: 7,
    images: ["speaker.png", "speaker2.png", "speaker3.png"],
    name: "JTL Bluetooth Speaker",
    price: 650.0,
    sale: true,
    stars: 0,
    discount: 5.0,
    colors: ["blue", "red", "black"],
    inStock: 9,
    sizes: [],
  },
];
